language: perl
matrix:
  include:
    - { perl: "system", os: "osx", env: "PERL_ZMQ_TEST_TARGET=ZMQ-Constants" }
    - { perl: "system", os: "osx", env: "PERL_ZMQ_TEST_TARGET=ZMQ-CZMQ" }
    - { perl: "system", os: "osx", env: "PERL_ZMQ_TEST_TARGET=ZMQ-LibCZMQ1" }
    - { perl: "system", os: "osx", env: "PERL_ZMQ_TEST_TARGET=ZMQ-LibZMQ2" }
    - { perl: "system", os: "osx", env: "PERL_ZMQ_TEST_TARGET=ZMQ-LibZMQ3" }
    - { perl: "system", os: "osx", env: "PERL_ZMQ_TEST_TARGET=ZMQ-LibZMQ4" }
    - { perl: "system", os: "osx", env: "PERL_ZMQ_TEST_TARGET=ZMQ" }
perl:
  - "5.20"
  - "5.22"
  - "5.24"
install: "perl -e 1" # dummy
script: "perl ./.TRAVIS.PL"
sudo: false
addons:
  apt:
    packages:
      - uuid-dev
env:
  - PERL_ZMQ_TEST_TARGET=ZMQ-Constants
  - PERL_ZMQ_TEST_TARGET=ZMQ-CZMQ
  - PERL_ZMQ_TEST_TARGET=ZMQ-LibCZMQ1
  - PERL_ZMQ_TEST_TARGET=ZMQ-LibZMQ2
  - PERL_ZMQ_TEST_TARGET=ZMQ-LibZMQ3
  - PERL_ZMQ_TEST_TARGET=ZMQ-LibZMQ4
  - PERL_ZMQ_TEST_TARGET=ZMQ
