language: perl
perl:
  - "5.20"
  - "5.22"
install: "perl -e 1" # dummy
script: "perl ./.TRAVIS.PL"
sudo: false
addons:
  apt:
    packages:
      - uuid-dev
env:
  - PERL_ZMQ_TEST_TARGET=ZMQ-Constants
  - PERL_ZMQ_TEST_TARGET=ZMQ-CZMQ
  - PERL_ZMQ_TEST_TARGET=ZMQ-LibCZMQ1
  - PERL_ZMQ_TEST_TARGET=ZMQ-LibZMQ2
  - PERL_ZMQ_TEST_TARGET=ZMQ-LibZMQ3
  - PERL_ZMQ_TEST_TARGET=ZMQ
